name: ci

on: push

jobs:
  ci: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
    env:
      PORT: ${{ secrets.SSH_PORT }}
      SERVER_SECRET: ${{ secrets.SERVER_SECRET }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      CLONE_TOKEN: ${{ secrets.CLONE_TOKEN }}
      PLATFORM_URI: ${{ secrets.PLATFORM_URI }}
      SERVER_EMAIL: ${{ secrets.SERVER_EMAIL }}
      SERVER_URI: ${{ secrets.SERVER_URI }}
